# Deploy branch is followed by Posit Connect
name: Update Requirements on Deploy Branch

on:
  push:
    branches:
      - main # Trigger when pushing to main
  pull_request:
    branches:
      - main # Trigger on pull requests to main

jobs:
  ci:
    env:
      UV_SYSTEM_PYTHON: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Make shinylive deployment in site
        run: uv run shinylive export abloc site

      - name: Upload website artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v1
        with:
          path: "site/"
