name: Deploy to ShinyApps.io
# useful links : https://docs.posit.co/shinyapps.io/guide/getting_started/#working-with-shiny-for-python

on:
  push:
    branches:
      - main # Trigger when pushing to main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-shiny:
    env:
      UV_SYSTEM_PYTHON: true
      SHINY_USERNAME: ${{ vars.USER_NAME }}
      SHINY_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
      SHINY_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      APP_NAME: ${{ vars.APP_NAME }}
      APP_ID: ${{ vars.APP_ID }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Deploy to ShinyApps.io
        run: |
          uv run rsconnect add --account $SHINY_USERNAME --name $SHINY_USERNAME --token $SHINY_TOKEN --secret $SHINY_SECRET
          uv run rsconnect deploy shiny . --name $SHINY_USERNAME --title $APP_NAME --app-id $APP_ID
